config/routes.rb
Rails.application.routes.draw do

  resources :employees
  resources :companies do
    collection { post :import }
  end

  devise_for :users
  get 'home/index'

  get 'home/about'

  get 'home/contact'

  get 'home/faqs'

  get 'home/pricing'

  get 'home/features'
  resources :invoices do
    resources :purchases, except: [:index], controller: 'invoices/purchases'
  end

  root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enterpriseape2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", home_index_path %></li>
      <li><%= link_to "About", home_about_path %></li>
      <li><%= link_to "Features", home_features_path %></li>
      <li><%= link_to "Invoices", invoices_path %></li>

      <% if current_user %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <div class='btn-group pull-right right-nav'>
        <button type="button" class="btn btn-mini dropdown-toggle" data-toggle="dropdown">Admin
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Invoices", invoices_path %></li>
          <li><%= link_to "Employees", employees_path %></li>
        </ul>
      </div>
      <% else %>
        <li><%= link_to "Sign-in", user_session_path, method: :post %><li>
        <li><%= link_to "Sign-up", new_user_registration_path, method: :get %><li>
      <% end %>

    </ul>

    <% if flash[:notice] %>
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:notice] %>
	</div>
<% elsif flash[:error] %>
	<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:error] %>
	</div>
<% elsif flash[:alert] %>
	<div class="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:alert] %>
	</div>
<% end %>

    <!--p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
</div>

</body>
</html>